apiVersion: apps/v1
kind: Deployment
metadata:
  name: fog-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fog-service
  template:
    metadata:
      labels:
        app: fog-service
    spec:
      containers:
      - name: fog-service
        image: cmkd/fog-service:latest
        ports:
        - containerPort: 8001
        resources:
          limits:
            memory: "2Gi"
            cpu: "1"
          requests:
            memory: "1Gi"
            cpu: "0.5"
---
apiVersion: v1
kind: Service
metadata:
  name: fog-service
spec:
  selector:
    app: fog-service
  ports:
  - port: 8001
    targetPort: 8001
  type: LoadBalancer